// English labels for the everyday workflow. Russian source labels remain stable keys.
// Technical reports returned by the Python core retain their original language.
extension L10n {
    static let english: [String: String] = [
        "Добро пожаловать в Proto-Mind": "Welcome to Proto-Mind",
        "Подключим вашу модель — и можно начинать.": "Connect your model and get started.",
        "Проверяем локальное ядро…": "Checking the local core…",
        "Локальное ядро готово": "Local core is ready",
        "Диалоги и память сохраняются на этом Mac. У каждого пользователя — свой профиль; замена приложения при обновлении его не удаляет.": "Conversations and memory are stored on this Mac. Each user has a separate profile; replacing the app during an update keeps it intact.",
        "Повторить проверку": "Check again",
        "Ваш аккаунт ChatGPT": "Your ChatGPT account",
        "Для текстовых задач нужен аккаунт с доступом к Codex. Встроенный Codex использует вашу подписку; API-ключ для этого не нужен.": "Text tasks require an account with Codex access. The bundled Codex uses your subscription; no API key is needed.",
        "Пока не удалось получить доступные модели. Проверьте вход ещё раз.": "Could not load available models yet. Check your sign-in again.",
        "Доступные модели получены.": "Available models loaded.",
        "Другой аккаунт…": "Use another account…",
        "Войти через ChatGPT…": "Sign in with ChatGPT…",
        "Проверить вход": "Check sign-in",
        "Завершите вход в браузере и вернитесь сюда. Если окно не обновилось, нажмите «Проверить вход».": "Finish signing in through your browser, then return here. If this screen has not updated, click “Check sign-in”.",
        "Разрешить облачную обработку": "Allow cloud processing",
        "При отправке задачи сообщения, выбранная память и вложения передаются OpenAI. Вход в аккаунт сам по себе этого разрешения не даёт.": "When you send a task, messages, selected memory and attachments are sent to OpenAI. Signing in alone does not grant this permission.",
        "Остальное — когда понадобится": "More when you need it",
        "Голос подключается в настройках с вашим OpenAI API-ключом и отдельной оплатой API. Доступ к файлам и Mac включается в диалоге.": "Set up voice in Settings with your own OpenAI API key and separate API billing. Enable file and Mac access within a conversation.",
        "Для управления экраном дополнительно нужен подписанный сервис Computer Use из Codex Desktop. Без него доступны чат и работа с файлами и командами при разрешённом доступе к Mac.": "Screen control also requires the signed Computer Use service from Codex Desktop. Without it, chat, file operations and commands remain available with the appropriate Mac access permission.",
        "Можно начать и с локальной моделью Ollama — выберите её в настройках после закрытия этого окна.": "You can also use a local Ollama model. Choose it in Settings after closing this screen.",
        "Настрою позже": "Set up later",
        "Начать работу": "Get started",
        "Поиск диалогов · ⌘F": "Search conversations · ⌘F",
        "Поиск диалогов": "Search conversations",
        "Новый диалог": "New conversation",
        "Новый чат": "New chat",
        "Очистить поиск": "Clear search",
        "История диалогов": "Conversation history",
        "Найти прошлую работу и продолжить": "Find earlier work and continue",
        "Файлы проекта": "Project files",
        "Браузер": "Browser",
        "Память проекта": "Project memory",
        "Сначала выберите папку проекта": "Choose a project folder first",
        "Текущие заметки и история этой папки": "Current notes and history for this folder",
        "Общая память": "Shared memory",
        "Библиотека": "Library",
        "Архив диалогов": "Archived conversations",
        "Диалоги": "Conversations",
        "Вернуться к диалогам": "Back to conversations",
        "Открыть архив": "Open archive",
        "Здесь появятся ваши диалоги": "Your conversations will appear here",
        "Ничего не найдено": "No matches",
        "Команды, диагностика и копии": "Commands, diagnostics and backups",
        "Инструменты": "Tools",
        "Команды": "Commands",
        "Диагностика": "Diagnostics",
        "Копии и восстановление": "Backups and recovery",
        "Название диалога": "Conversation title",
        "Название": "Title",
        "Отмена": "Cancel",
        "Сохранить": "Save",
        "Есть черновик": "Has a draft",
        " · Выполняется задача": " · Task running",
        "Переименовать…": "Rename…",
        "Вернуть из архива": "Unarchive",
        "В архив": "Archive",
        "Меню": "Menu",
        "Настройки и лимиты": "Settings and limits",
        "Настройки и лимиты Codex. Показан остаток лимитов аккаунта.": "Codex settings and limits. Shows your account's remaining allowance.",
        "Лимиты Codex · —": "Codex limits · —",
        "Нет входа в ChatGPT": "Not signed in to ChatGPT",
        "Осталось ": "Remaining ",
        "Лимиты Codex": "Codex limits",
        "Осталось": "Remaining",
        "Обновляю…": "Refreshing…",
        "Данные пока недоступны": "No data yet",
        "Данные устарели": "Data is out of date",
        "Настройки": "Settings",
        "Лимиты": "Limits",
        "Обычное окно": "Standard window",
        "Парящий режим": "Floating mode",
        "Чем займёмся?": "What shall we work on?",
        "Разберём идею, поработаем над проектом\nили вспомним важное.": "Explore an idea, work on a project\nor recall something important.",
        "Вернуться к работе": "Resume work",
        "Найти и продолжить прежний диалог": "Find and continue an earlier conversation",
        "Обсудить идею": "Discuss an idea",
        "Разложить мысли по полочкам": "Make sense of your thoughts",
        "Помоги мне разобраться с идеей: ": "Help me explore this idea: ",
        "Открыть проект": "Open a project",
        "Выбрать папку для работы": "Choose a folder to work in",
        "Вспомнить важное": "Recall something",
        "Открыть сохранённую память": "Open saved memory",
        "Или просто напишите сообщение ниже.": "Or just write a message below.",
        "Диалог в архиве": "Conversation archived",
        "Вернуть к диалогам": "Back to conversations",
        "Подключите ChatGPT в настройках, чтобы начать": "Connect ChatGPT in Settings to get started",
        "Продолжение предыдущей задачи": "Continuing an earlier task",
        "Отвязать": "Unlink",
        "Оставить текст как самостоятельный новый запрос": "Keep this text as an independent new request",
        "Уточнение к текущей задаче…": "Update the current task…",
        "Сообщение Proto-Mind…": "Message Proto-Mind…",
        "Добавить вложение": "Add attachment",
        "Изображение…": "Image…",
        "Страницы PDF…": "PDF pages…",
        "Файл проекта…": "Project file…",
        "Заметка проекта…": "Project note…",
        "Контекст, критерии, память и навыки": "Context, criteria, memory and skills",
        "Настройки запроса": "Request settings",
        "Контекст запроса": "Request context",
        "Что увидит модель перед отправкой": "What the model will see before you send",
        "Критерии результата": "Outcome criteria",
        "Как проверить, что задача решена": "How to check that the task is done",
        "Навыки": "Skills",
        "Подбирать автоматически": "Select automatically",
        "Короткий запрос модели для подбора навыков": "A short model request to choose skills",
        "Убрать ручной выбор": "Clear manual selection",
        "Встроенный набор…": "Built-in collection…",
        "Личная библиотека…": "Personal library…",
        "Вспоминать автоматически": "Recall automatically",
        "Предлагать новые заметки": "Suggest new notes",
        "Только сохранённые заметки этой папки. Новые записи — после вашего подтверждения.": "Only saved notes from this folder. New notes require your confirmation.",
        "Заметки проекта…": "Project notes…",
        "Выбор сохраняется для этого диалога. Заметки можно проверить в контексте запроса.": "Saved for this conversation. Review selected notes in the request context.",
        "Запросить остановку Codex. Локальные операции завершаются без прерывания; выполненные действия не откатываются.": "Request Codex to stop. Local operations finish without interruption; completed actions are not rolled back.",
        "Запросить остановку": "Request stop",
        "Отправить уточнение": "Send update",
        "Отправить сообщение": "Send message",
        "Сначала восстановите сохранение истории": "Restore history saving first",
        "Добавить к текущей задаче · Return. Свернуть · Esc": "Add to task · Return. Collapse · Esc",
        "Добавить к текущей задаче · Return. Остановить · Esc": "Add to task · Return. Stop · Esc",
        "Отправить · Return": "Send · Return",
        "Убрать вложение": "Remove attachment",
        " · до 6 000 символов для следующего сообщения": " · up to 6,000 characters for the next message",
        "Доступ к Mac": "Mac access",
        "Только чат": "Chat only",
        "Полный доступ к Mac включён": "Full Mac access enabled",
        "Только чат, инструменты выключены": "Chat only, tools are off",
        "Полный доступ к Mac. Stop и Esc не откатывают изменения.": "Full Mac access. Stop and Esc do not roll back changes.",
        "Модель отвечает без инструментов. Доступ к Mac включается отдельно.": "The model replies without tools. Enable Mac access separately.",
        "Файлы, терминал, интернет и экран доступны": "Files, terminal, internet and screen available",
        "Файлы, терминал и интернет доступны": "Files, terminal and internet available",
        "Выключить доступ к Mac": "Turn off Mac access",
        "Разрешить доступ к Mac…": "Allow Mac access…",
        "Открыть этот диалог в основном чате": "Open this conversation in the main chat",
        "Открыть диалог в основном чате": "Open conversation in the main chat",
        "Предыдущие сообщения": "Earlier messages",
        "Ещё одно пространство для мысли": "Another space to think",
        "Начните отдельную задачу. Её модель, сообщения и работа сохраняются в этом диалоге.": "Start a separate task. Its model, messages and work stay in this conversation.",
        "К последнему сообщению": "Jump to latest message",
        "Диалог недоступен": "Conversation unavailable",
        "Он мог быть удалён или заменён при восстановлении истории.": "It may have been removed or replaced during history recovery.",
        "Убрать": "Remove",
        "Дополнение к задаче…": "Add to the task…",
        "Прикрепить файл в панели": "Attach a file in this panel",
        "Прикрепить текстовый файл проекта или PDF": "Attach a project text file or PDF",
        "Папка, доступ и память": "Folder, access and memory",
        "Модель этого диалога": "This conversation's model",
        "Остановить задачу в панели": "Stop task in panel",
        "Отправить в панель": "Send to panel",
        "Тестовый режим": "Test mode",
        "Этот диалог": "This conversation",
        "Выбрать папку проекта": "Choose project folder",
        "Разрешить доступ к Mac": "Allow Mac access",
        "Подбирать навыки": "Select skills",
        "Вспоминать заметки проекта": "Recall project notes",
        "Все настройки диалога": "All conversation settings",
        "Модель диалога": "Conversation model",
        "Усилие": "Effort",
        "Авто": "Auto",
        "ID модели": "Model ID",
        "Выбрать модель": "Choose a model",
        "Закрыть вкладку": "Close tab",
        "Добавить вкладку": "Add tab",
        "Добавить вкладку · ": "Add tab · ",
        "Вернуть две панели": "Restore both panels",
        "Развернуть до боковой колонки": "Expand to the sidebar",
        "Свернуть · ": "Collapse · ",
        "Развернуть · ": "Expand · ",
        "Закрыть терминал?": "Close terminal?",
        "Закрыть терминал": "Close terminal",
        "Это завершит терминальный сеанс этой вкладки. Задачи в диалогах PM продолжат работу.": "This ends this tab's terminal session. Tasks in PM conversations will keep running.",
        "Новый диалог PM": "New PM conversation",
        "Открыть диалог": "Open conversation",
        "Браузер / веб-приложение": "Browser / web app",
        "Терминал": "Terminal",
        "Другой CLI": "Another CLI",
        "Claude Code не установлен. Установите CLI и войдите в свой аккаунт; затем откройте его здесь.": "Claude Code is not installed. Install the CLI and sign in to your account, then open it here.",
        "Выбрать исполняемый файл…": "Choose executable…",
        "Открыть файл…": "Open file…",
        "Файлы основного проекта": "Main project's files",
        "Вернуть размер": "Restore size",
        "Развернуть панель": "Expand panel",
        "Откройте рядом": "Open beside your work",
        "Диалог, страницу или инструменты для работы.": "A conversation, a page or tools for your work.",
        "Диалог PM": "PM conversation",
        "Копировать ответ": "Copy response",
        "К диалогу": "Go to conversation",
        "Диалог": "Conversation",
        "Запустить CLI": "Launch CLI",
        "Новая страница": "New page",
        "Просмотр": "Preview",
        "Исходник": "Source",
        "Обновить файл": "Refresh file",
        "Прикрепить к сообщению": "Attach to message",
        "Прикрепить файл к сообщению": "Attach file to message",
        "Показаны первые 12 000 символов. Полный файл доступен через «Открыть».": "Showing the first 12,000 characters. Use “Open” for the complete file.",
        "Файл открыт из другого диалога или папки.": "This file belongs to another conversation or folder.",
        "Прикрепить изображение к сообщению": "Attach image to message",
        "Прикрепить выбранные страницы": "Attach selected pages",
        "Прикрепить страницы PDF": "Attach PDF pages",
        "Текст PDF": "PDF text",
        "Предыдущая страница PDF": "Previous PDF page",
        "Следующая страница PDF": "Next PDF page",
        "На этой странице нет текстового слоя.": "This page has no text layer.",
        "Показано начало текста страницы.": "Showing the beginning of the page text.",
        "Оригинальное оформление — через «Открыть».": "Use “Open” to see the original layout.",
        "Открыть в TextEdit": "Open in TextEdit",
        "Открыть в Просмотре": "Open in Preview",
        "Показать в Finder": "Show in Finder",
        "Открыть": "Open",
        "Введите адрес сайта, например https://example.com.": "Enter a website address, such as https://example.com.",
        "Здесь открываются адреса http и https. Локальные файлы открывайте через «Файлы».": "This browser opens http and https addresses. Use Files to open local documents.",
        "Этот адрес не открывается во встроенном браузере.": "This address cannot be opened in the built-in browser.",
        "Для скачивания откройте страницу во внешнем браузере.": "Open the page in your external browser to download files.",
        "Этот файл можно скачать во внешнем браузере.": "Download this file with your external browser.",
        "Страница остановилась. Нажмите «Обновить», чтобы загрузить её заново.": "The page stopped. Click Reload to load it again.",
        "Назад": "Back",
        "Вперёд": "Forward",
        "Остановить загрузку": "Stop loading",
        "Обновить страницу": "Reload page",
        "Адрес сайта": "Website address",
        "Передать страницу или выделение в задачу": "Use this page or selection in a task",
        "Передать в задачу": "Use in a task",
        "Открыть во внешнем браузере": "Open in external browser",
        "Откройте страницу рядом с разговором": "Open a page beside the conversation",
        "Введите адрес выше или нажмите ссылку в ответе.\nПередайте текст кнопкой «В задачу» или голосом.\nВходы на сайты сохраняются только до закрытия вкладки.": "Enter an address above or follow a link in a reply.\nUse the page in a task with the toolbar button or your voice.\nWebsite sessions last until the tab closes.",
        "Модели": "Models",
        "Голос": "Voice",
        "Оформление": "Appearance",
        "Общение": "Conversation style",
        "Подключения": "Connections",
        "Данные и копии": "Data and backups",
        "Дополнительно": "Advanced",
        "Выберите, с какой моделью продолжить этот диалог.": "Choose the model for this conversation.",
        "Диктовка сообщений и голосовой разговор.": "Message dictation and voice conversations.",
        "Прозрачность парящего рабочего пространства.": "Floating workspace transparency.",
        "Характер общения и использование памяти.": "Conversation style and memory use.",
        "Сервисы, которыми вы пользуетесь в работе.": "Services you use for work.",
        "Ваши диалоги и способы их восстановить.": "Your conversations and ways to restore them.",
        "Доступ, сессии и технические сведения.": "Access, sessions and technical details.",
        "Настройки Proto-Mind": "Proto-Mind settings",
        "Начать новую сессию ChatGPT?": "Start a new ChatGPT session?",
        "Начать новую сессию": "Start new session",
        "Следующее сообщение начнёт новую сессию модели. Диалоги Proto-Mind и прежние записи Codex сохранятся. Полный доступ к Mac будет выключен.": "The next message will start a new model session. Proto-Mind conversations and earlier Codex records will remain. Full Mac access will be turned off.",
        "Включить Brother?": "Enable Brother?",
        "Проверить и включить": "Check and enable",
        "Совместимость будет проверена повторно. Изменение действует со следующего сообщения и не добавляет доступа к файлам или инструментам.": "Compatibility will be checked again. The change applies to the next message and does not grant file or tool access.",
        "Диктовка": "Dictation",
        "Голосовой разговор": "Voice conversation",
        "Разрешить обработку в OpenAI": "Allow processing by OpenAI",
        "Кнопка голосовой волны рядом с «Меню» сразу начинает разговор. После запуска приложения голос остаётся выключенным.": "The waveform button beside Menu starts a conversation immediately. Voice stays off when you launch the app.",
        "Использование API": "API usage",
        "GPT Live 1: $0,05 за минуту подключённого разговора. Обработка команд GPT-5.6 Luna оплачивается дополнительно по тарифу API. Подписка ChatGPT не оплачивает этот голосовой канал.": "GPT Live 1: $0.05 per minute of connected conversation. Command processing by GPT-5.6 Luna is billed separately at API rates. Your ChatGPT subscription does not pay for this voice channel.",
        "Language / Язык": "Language / Язык",
        "Память и навыки": "Memory and skills",
        "Заметки проекта и автоматический подбор навыков настраиваются для каждого диалога через кнопку рядом с вложениями.": "Configure project notes and automatic skill selection for each conversation using the button beside attachments.",
        "Перед отправкой можно посмотреть, какие сведения попадут в запрос, в разделе «Контекст запроса».": "Before sending, review what will enter the request in “Request context”.",
        "О приложении": "About",
        "Версия": "Version",
        "Локальная сборка": "Local build",
        "Технические сведения": "Technical details",
        "В этом диалоге": "In this conversation",
        "Источник модели": "Model source",
        "ChatGPT · по подписке": "ChatGPT · subscription",
        "Ollama · на этом Mac": "Ollama · on this Mac",
        "Модель через API": "Model via API",
        "Тестовый режим · без модели": "Test mode · no model",
        "Настроить API-подключения": "Set up API connections",
        "Модель Ollama": "Ollama model",
        "Сообщения обрабатываются локально. Для работы запустите Ollama на этом Mac.": "Messages are processed locally. Start Ollama on this Mac to use it.",
        "Проверить подключение": "Check connection",
        "Доступна": "Available",
        "Недоступна": "Unavailable",
        "Установленные модели": "Installed models",
        "Модель": "Model",
        "По умолчанию для аккаунта": "Account default",
        "Глубина рассуждения": "Reasoning effort",
        "По умолчанию": "Default",
        "Обновить список": "Refresh list",
        "Сбросить выбор": "Reset selection",
        "Выбор сохраняется для этого диалога. Доступные модели и уровни зависят от аккаунта.": "Saved for this conversation. Available models and effort levels depend on your account.",
        "Этот режим проверяет приложение без запроса к модели. Он не выполняет задачи и не анализирует сообщения.": "This mode checks the app without calling a model. It does not perform tasks or analyze messages.",
        "Аккаунт ChatGPT": "ChatGPT account",
        "Помощь с первым подключением…": "First connection help…",
        "Вход ещё не проверен": "Sign-in not checked yet",
        "Подключено": "Connected",
        "Не подключено": "Not connected",
        "Использование и лимиты Codex…": "Codex usage and limits…",
        "Выйти": "Sign out",
        "Завершите вход в браузере и нажмите «Проверить вход».": "Finish signing in through your browser, then click “Check sign-in”.",
        "Сообщения, выбранная память и прикреплённые материалы передаются OpenAI. Разрешение действует на этом Mac и сохраняется после перезапуска.": "Messages, selected memory and attachments are sent to OpenAI. This permission is saved on this Mac and persists across restarts.",
        "Как работает подключение": "How the connection works",
        "Proto-Mind использует официальный Codex и отдельный профиль входа. API-ключ не нужен. Сессии продолжаются между сообщениями; при создании новой сессии добавляется до 12 локальных реплик. Данные входа и настройки Codex Desktop не используются.": "Proto-Mind uses the official Codex with a separate sign-in profile. No API key is needed. Sessions continue between messages; a new session includes up to 12 local messages. Codex Desktop credentials and settings are not used.",
        "Характер общения · Brother": "Conversation style · Brother",
        "Состояние": "Status",
        "Включён": "Enabled",
        "Обычный режим": "Standard mode",
        "Brother задаёт устойчивый характер общения и использует память, уже выбранную ядром для ответа.": "Brother provides a consistent conversation style and uses the memory already selected by the core for the response.",
        "Вернуться к обычному режиму": "Return to standard mode",
        "Проверяем совместимость…": "Checking compatibility…",
        "Проверить и включить…": "Check and enable…",
        "Выберите ChatGPT или Ollama для включения Brother.": "Choose ChatGPT or Ollama to enable Brother.",
        "Изменение действует со следующего сообщения. Оно не даёт дополнительных разрешений и не стирает прежнюю историю модели.": "Applies to the next message. Grants no additional permissions and does not erase previous model history.",
        "Сведения о проверке": "Check details",
        "Проверка ещё не выполнялась.": "Not checked yet.",
        "Persona не меняет Context Injection, не создаёт скрытых записей и проверяет совместимость перед каждым ответом.": "Persona does not change Context Injection, create hidden records, or skip compatibility checks before each response.",
        "Все локальные данные": "All local data",
        "Диалоги, память, журнал работы и настройки — в одной копии с проверкой файлов и восстановлением.": "Conversations, memory, work logs and settings in one backup with file verification and recovery.",
        "Полная копия данных…": "Full data backup…",
        "Копии диалогов": "Conversation backups",
        "Сохраните отдельную копию или вернитесь к предыдущему состоянию истории.": "Save a separate copy or restore an earlier conversation history.",
        "Копии и восстановление…": "Backups and recovery…",
        "В копию входят сообщения, черновики и настройки диалогов. Память, журнал задач, облачные сессии и исходные вложения хранятся отдельно.": "Includes messages, drafts and conversation settings. Memory, task logs, cloud sessions and original attachments are stored separately.",
        "На этом Mac": "On this Mac",
        "Диалоги хранятся в приватной папке приложения. Локальные снимки помогают восстановить историю, а копия на другом диске — защититься от потери данных.": "Conversations are stored in the app's private folder. Local snapshots help recover history; a copy on another drive helps protect against data loss.",
        "Расположение данных": "Data location",
        "В профиле Codex могут храниться полные сообщения и вывод инструментов. Папка содержит личные данные и не предназначена для публикации.": "The Codex profile may contain complete messages and tool output. This folder contains personal data and is not intended for publication.",
        "Полный доступ включён": "Full access enabled",
        "Только чат · инструменты выключены": "Chat only · tools off",
        "Доступ включается отдельно для диалога возле поля сообщения и сохраняется после перезапуска. Он разрешает работу с файлами, терминалом и интернетом, а при доступности — управление экраном. Смена папки или провайдера отключает его.": "Enable access for each conversation beside the message field. It persists across restarts and permits files, terminal, internet and, where available, screen control. Changing the folder or provider turns it off.",
        "Выключить доступ": "Turn off access",
        "Ограничения и журнал действий": "Limits and activity log",
        "Доступ охватывает весь Mac в пределах прав пользователя. Экран может обрабатываться OpenAI. Остановка не откатывает уже выполненные действия. В журнале управления экраном остаются тип действия и приложение, без скриншотов, координат и введённого текста. Это не полный аудит.": "Access covers this Mac within your user's permissions. The screen may be processed by OpenAI. Stopping does not undo completed actions. Screen-control logs retain action type and app, without screenshots, coordinates or entered text. This is not a complete audit.",
        "Подключается только проверенная служба OpenAI Computer Use. Прочие MCP, hooks и субагенты выключены. Зависший вызов ограничен 30 секундами и не повторяется автоматически под другим именем приложения.": "Only the verified OpenAI Computer Use service is connected. Other MCP services, hooks and subagents are disabled. A stalled call is limited to 30 seconds and is not automatically retried under another app name.",
        "Сессия модели": "Model session",
        "Обновить статус": "Refresh status",
        "Начать заново…": "Start over…",
        "Технические сведения о сессии": "Session technical details",
        "Для чата и полного доступа создаются разные сессии Codex. Следующие сообщения продолжают соответствующую сессию. Обновление инструкций может начать новую сессию, сохраняя прежнюю историю.": "Chat and full access use separate Codex sessions. Later messages continue the corresponding session. Updated instructions may start a new session while preserving the previous history.",
        "Старая сессия сохранена, но не возобновляется автоматически.": "The old session is saved but will not resume automatically.",
        "Цепочка диалога · Session Spine": "Conversation chain · Session Spine",
        "Один ход записан": "One turn recorded",
        "Ход подготовлен до перезапуска": "Turn prepared before restart",
        "Запись не включена": "Recording is off",
        "Экспериментальная связь ответа с сохранёнными данными о его выполнении. Открывается из меню «Подробнее» под связанным ответом.": "An experimental link between a response and saved execution evidence. Open it from More below a linked response.",
        "Отменить подготовку": "Cancel preparation",
        "P2j/P2k действуют только до перезапуска и ничего не записывают. P2l требует новой проверки, подтверждения и точной фразы для одного связанного хода. Старые ответы без Turn Lineage не переносятся. Существующие ошибки требуют ручной проверки; автоматического ремонта нет.": "P2j/P2k last until restart and do not write data. P2l requires a fresh check, confirmation and an exact phrase for one linked turn. Older responses without Turn Lineage are not transferred. Existing errors require manual inspection; there is no automatic repair.",
        "Рабочие панели внутри окна": "Panels inside the workspace",
        "Показывать нижнюю панель": "Show lower panel",
        "По умолчанию справа одна панель. Вторая располагается под ней. Отдельные окна парящего режима включаются кнопками 1 и 2 слева от кубика.": "One panel is shown on the right by default. The second goes below it. Toggle separate floating windows with buttons 1 and 2 beside the cube.",
        "Боковые окна": "Side windows",
        "Боковые окна · ⌥⌘1 / ⌥⌘2": "Side windows · ⌥⌘1 / ⌥⌘2",
        "По умолчанию справа одна панель. Вторая располагается под ней. Отдельные боковые окна доступны в обоих режимах: через кнопку в верхней панели или кнопки 1 и 2 у кубика.": "One panel is shown on the right by default. The second goes below it. Separate side windows are available in both modes: use the toolbar button or buttons 1 and 2 beside the cube.",
        "В режиме кубика боковые окна появляются и скрываются вместе с чатом. Этот переключатель оставляет отлепленные окна видимыми. При смене режима открытые окна сохраняются.": "In cube mode, side windows appear and hide with the chat. This option keeps detached windows visible. Open windows stay open when switching modes.",
        "Слева — плотный фон, справа — прозрачный. Текст и кнопки остаются чёткими. Прозрачность чата и колонки применяется в режиме кубика, боковых окон — в обоих режимах. Значения сохраняются после перезапуска.": "Left makes the background solid; right makes it transparent. Text and controls stay clear. Chat and sidebar transparency applies in cube mode; side window transparency applies in both modes. Values persist across restarts.",
        "Оставлять отлепленные окна на экране": "Keep detached windows visible",
        "По умолчанию оба боковых окна появляются и скрываются вместе с чатом через кубик. Этот переключатель позволяет оставлять отлепленные окна видимыми.": "By default both side windows appear and hide with the chat through the cube. Enable this option to keep detached windows visible.",
        "Прозрачность фона": "Background transparency",
        "Окно чата": "Chat window",
        "Левая колонка": "Left sidebar",
        "Боковое ": "Side ",
        "Слева — плотный фон, справа — прозрачный. Текст и кнопки остаются чёткими. Изменения видны сразу в парящем режиме и сохраняются после перезапуска.": "Left makes the background solid; right makes it transparent. Text and controls stay clear. Changes appear immediately in floating mode and persist across restarts.",
        "В macOS включено уменьшение прозрачности. Фон остаётся непрозрачным, выбранные значения сохранены.": "Reduce Transparency is enabled in macOS. Backgrounds remain solid; your selected values are saved.",
        "Вернуть исходную прозрачность": "Reset transparency",
        "Включить парящий режим": "Enable floating mode",
        "Голосовой разговор подключён": "Voice conversation connected",
        "Подключение голосового разговора": "Connecting voice conversation",
        "Поговорить с Proto-Mind": "Talk to Proto-Mind",
        "Голос Proto-Mind": "Proto-Mind voice",
        "Настройки голоса": "Voice settings",
        "Свернуть разговор": "Minimize conversation",
        "Обсудим и сделаем": "Let's discuss it and get it done",
        "«Открой проект…»\n«Создай задачу…»\n«Добавь к текущей задаче…»\n«Как продвигается работа?»": "“Open the project…”\n“Create a task…”\n“Update the current task…”\n“How is the work going?”",
        "Работа выполняется выбранной моделью и с доступом соответствующего диалога.": "Work uses the selected task's model and access permissions.",
        "Микрофон выключен": "Microphone muted",
        "Слушаю": "Listening",
        "Подключаюсь…": "Connecting…",
        "Уровень микрофона": "Microphone level",
        "Включить микрофон": "Unmute microphone",
        "Микрофон": "Microphone",
        "Завершаю…": "Ending…",
        "Завершить": "End call",
        "Начать разговор": "Start conversation",
        "Можно свернуть и продолжать говорить. «Завершить» отключает голос; рабочие задачи продолжаются.": "Minimize and keep talking. End Call stops voice; accepted tasks keep running.",
        "Микрофон и речь передаются OpenAI. $0,05/мин разговора + обработка команд API; отдельно от подписки ChatGPT.": "Microphone audio and speech are sent to OpenAI. $0.05/minute of conversation plus API command processing; billed separately from ChatGPT.",
        "API-ключ сохранён": "API key saved",
        "Подключите OpenAI API": "Connect OpenAI API",
        "Новый ключ для замены": "Replacement key",
        "API-ключ OpenAI": "OpenAI API key",
        "Сохранить ключ": "Save key",
        "Ключ сохранён в Связке ключей macOS.": "Key saved in macOS Keychain.",
        "Удалить": "Delete",
        "Ключ удалён с этого Mac.": "Key removed from this Mac.",
        "Ключ хранится на этом Mac, отдельно от истории и резервных копий. Разговор включается только по кнопке; после запуска приложения микрофон выключен.": "The key is stored on this Mac, separately from history and backups. Voice starts only when you press the button; the microphone is off when the app launches.",
        "Во время разговора OpenAI получает звук, названия проектов и результаты запрошенных задач.": "During a call, OpenAI receives audio, project names and the results of requested tasks.",
        "Голос: GPT Live 1 · команды: GPT-5.6 Luna. Работа над проектами использует модель выбранной задачи и её память.": "Voice: GPT Live 1 · commands: GPT-5.6 Luna. Project work uses the selected task's model and memory.",
        "Реплики разговора видны до следующего звонка. Поручения и уточнения сохраняются в истории соответствующих задач; аудиозапись на диск не ведётся.": "Call messages remain visible until the next call. Instructions and updates are saved in the corresponding task histories; audio is not recorded to disk.",
        "Открыть API-ключи OpenAI": "Open OpenAI API keys",
        "Вернуть миниатюру": "Restore miniature",
        "Развернуть окно": "Expand window",
        "Миниатюра · ": "Miniature · ",
        "Развернуть окно · ": "Expand window · ",
        "Вернуть наверх справа · исходный размер": "Return to upper right · default size",
        "Вернуть вниз справа · исходный размер": "Return to lower right · default size",
        "Вернуть на место · ": "Return to position · ",
        "Скрыть окно": "Hide window",
        "Скрыть · ": "Hide · ",
        "К окну": "Go to window",
        "Изменить высоту боковых окон": "Resize side windows",
        "Высота боковых окон": "Side window height",
        "Укажите имя, модель и базовый адрес API (HTTPS; HTTP разрешён только на этом Mac).": "Enter a name, model and API base URL (HTTPS; HTTP is allowed only on this Mac).",
        "Вставьте API-ключ целиком, без пробелов и переносов строк.": "Paste the entire API key without spaces or line breaks.",
        "Можно сохранить до 20 API-подключений.": "You can save up to 20 API connections.",
        "Выберите API-подключение для этого диалога.": "Choose an API connection for this conversation.",
        "Модели через API": "Models via API",
        "Изменить": "Edit",
        "Удалить подключение и его ключ": "Delete connection and its key",
        "Добавить API-подключение": "Add API connection",
        "Мой OpenAI / локальный сервер": "My OpenAI / local server",
        "Формат": "Format",
        "OpenAI-совместимый Chat Completions": "OpenAI-compatible Chat Completions",
        "Базовый URL": "Base URL",
        "Точное имя из каталога провайдера": "Exact name from the provider's model catalog",
        "API-ключ": "API key",
        "Оставьте пустым, чтобы сохранить прежний": "Leave blank to keep the existing key",
        "Ключ отправляется только на этот адрес и хранится в Связке ключей. API оплачивается отдельно от подписки ChatGPT. Локальному серверу ключ не обязателен.": "The key is sent only to this address and stored in Keychain. API billing is separate from ChatGPT. Local servers do not require a key.",
        "Подключение сохранено. Выберите его в меню модели любого диалога.": "Connection saved. Choose it from the model menu in any conversation.",
        "API поддерживает диалог, память ядра, выбранные заметки, текстовые файлы и PDF. Инструменты Mac и уточнения во время выполнения доступны в маршруте Codex.": "API supports chat, core memory, selected notes, text files and PDFs. Mac tools and updates during execution are available through Codex.",
        "API-подключение": "API connection",
        "Выберите подключение": "Choose a connection",
        "ChatGPT · подписка": "ChatGPT · subscription",
        "Ollama · локально": "Ollama · local",
        "Подключить API…": "Connect API…",
        "Сохраняй важные факты, уточняй решения и убирай то, что больше не актуально.": "Save important facts, refine decisions and remove what no longer applies.",
        "Текущие заметки этой папки могут подбираться к новым запросам, если включена память проекта. При отправке через Codex выбранные сведения попадут в облачный контекст.": "Current notes for this folder can be recalled for new requests when project memory is enabled. When sending through Codex, selected notes enter the cloud context.",
        "Найти заметку": "Search notes",
        "Найти": "Search",
        "История": "History",
        "Предыдущие": "Previous",
        "Следующие": "Next",
        "Подходящих заметок нет.": "No matching notes.",
        "Подходящих заметок нет. Убранные и прежние версии доступны в истории.": "No matching notes. Removed notes and previous versions are available in history.",
        "Это сохранённое утверждение пользователя. Содержимое записи проверено; достоверность факта отдельно не оценивалась.": "This is a saved user statement. Record integrity has been checked; the factual claim has not been independently verified.",
        "К следующему сообщению": "Use in next message",
        "Убрать из памяти проекта": "Remove from project memory",
        "Вернуть в память проекта": "Restore to project memory",
        "Убранная заметка хранится в истории и не подбирается к новым запросам. Уже отправленные сообщения и контекст провайдера сохраняются.": "Removed notes stay in history and are excluded from future recall. Previously sent messages and provider context remain.",
        "Подробности записи": "Record details",
        "Новая заметка": "New note",
        "Изменить заметку": "Edit note",
        "Тип": "Type",
        "Содержание · до 4 000 символов": "Content · up to 4,000 characters",
        "Источник или пояснение · необязательно": "Source or explanation · optional",
        "После сохранения прежняя версия останется в истории и перестанет подбираться к запросам.": "After saving, the previous version stays in history and is excluded from future recall.",
        "Сохранить заметку": "Save note",
        "Сохранить изменения": "Save changes",
        "Эти действия меняют только память выбранного проекта. Они не вызывают модель, не запускают задачу и не прикрепляют заметку автоматически. Общая старая память хранится отдельно.": "These actions change only the selected project's memory. They do not call a model, start a task or attach a note automatically. Older shared memory is stored separately.",
        "Явно выбранная заметка проекта. Перед Send проверяются проект, актуальность и SHA. Не автоматический recall.": "An explicitly selected project note. Its project, freshness and hash are checked before sending. This is not automatic recall.",
        "Без рассуждения": "No reasoning",
        "Минимальное": "Minimal",
        "Лёгкое": "Low",
        "Среднее": "Medium",
        "Высокое": "High",
        "Очень высокое": "Very high",
        "Макс.": "Max",
        "Ультра": "Ultra",
        "менее секунды": "less than a second",
        "Подключаюсь": "Connecting",
        "Пишу ответ": "Writing a response",
        "Работаю": "Working",
        "Редактирует файлы": "Editing files",
        "Редактирование файлов": "File edits",
        "выполняет команды": "running commands",
        "команды в терминале": "terminal commands",
        "ищет в интернете": "searching the web",
        "поиск в интернете": "web search",
        "работает с приложениями": "working with apps",
        "работа с приложениями": "app actions",
        "смотрит изображения": "viewing images",
        "просмотр изображений": "image viewing",
        "Действия инструментов": "Tool activity",
        "Ход работы: ": "Activity: ",
        "Показана часть хода работы": "Showing part of the activity",
        "План работы": "Work plan",
        "Сжатие контекста": "Context compaction",
        "Ядро Proto-Mind": "Proto-Mind core",
        "Оставить открытым": "Keep open",
        "Свернуть в ядро": "Collapse to core",
        "Открыть Proto-Mind": "Open Proto-Mind",
        "Боковое окно 1": "Side window 1",
        "Боковое окно 2": "Side window 2",
        "Наведите курсор, чтобы заглянуть в чат и боковую панель. Нажмите, чтобы оставить открытыми, ещё раз — свернуть. Перетащите в удобное место.": "Hover to preview the chat and sidebar. Click to keep them open, then again to collapse. Drag to a convenient spot.",
        "Подтвердить команду": "Confirm command",
        "Эта команда меняет состояние или требует повышенного внимания. Модель не запрашивала её выполнение: ниже именно ваш ввод.": "This command changes state or needs extra attention. The model did not request it: this is your exact input.",
        "Внутренние approval/token/preview-гейты Proto-Mind по-прежнему действуют.": "Proto-Mind's internal approval, token and preview checks still apply.",
        "Выполнить мой ввод": "Run my input",
        "Открыть Automation": "Open Automation",
        "Журнал работы": "Work log",
        "Журнал работы и ручное продолжение": "Work log and manual continuation",
        "Две рабочие панели": "Two workspace panels",
        "Рабочие панели": "Workspace panels",
        "Папка проекта": "Project folder",
        "Ширина рабочих панелей": "Workspace panel width",
        "Высота рабочих панелей": "Workspace panel height",
        "История хранится полностью; загружается только следующая часть интерфейса": "Full history is preserved; only the next part of the interface is loaded",
        "Показать следующие сообщения": "Show more messages",
        "Нужна проверка": "Needs attention",
        "Локальное ядро": "Local core",
        "Не удалось подтвердить отключение Computer Use. Если управление осталось активно, остановите его в панели Computer Use.": "Could not confirm Computer Use release. If control is still active, stop it in the Computer Use panel.",
        "Результат": "Result",
        "Открыть ответ рядом": "Open response beside chat",
        "Подробнее": "More",
        "Об ответе": "About this response",
        "Скрыть исходный отчёт": "Hide raw report",
        "Исходный отчёт": "Raw report",
        "Ход этой задачи": "This task's activity",
        "Подробнее об ответе": "More about this response",
        "Локальный просмотр исходного файла с проверкой SHA-256. Изображение не отправляется повторно.": "Local preview of the original file with SHA-256 verification. The image is not sent again.",
        "Локально прочитать выбранные страницы с проверкой SHA-256; без повторной отправки": "Read selected pages locally with SHA-256 verification, without resending",
        "Сообщение Proto-Mind": "Message Proto-Mind",
        "Наверх": "Up",
        "Остановить": "Stop",
        "Настройки…": "Settings…",
        "Каталог команд": "Command catalog",
        "Новая страница в панели": "New page in panel",
        "Инспектор ответа": "Response inspector",
        "Обновить обзор": "Refresh overview",
        "Использование Codex…": "Codex usage…",
        "Копии диалогов…": "Conversation backups…",
        "Переключить парящий режим": "Toggle floating mode",
        "Верхняя панель": "Upper panel",
        "Нижняя панель": "Lower panel",
        "Пять часов": "Five hours",
        "Неделя": "Week",
        "5 ч": "5 h",
        "Для этого диалога": "For this conversation",
        "Обновить доступные модели": "Refresh available models",
        "Выбранное усилие сейчас недоступно": "The selected effort is currently unavailable",
        "Автоматически": "Automatic",
        "Настройки модели": "Model settings",
        "Модель Codex": "Codex model",
        "Усилие рассуждения": "Reasoning effort",
        "Завершите голосовой разговор, чтобы диктовать текст": "End the voice conversation to dictate text",
        "Закончить диктовку": "Finish dictation",
        "Диктовать сообщение · ": "Dictate message · ",
        "Диктовка сообщения": "Message dictation",
        "Подключаю микрофон…": "Connecting microphone…",
        "Завершаю диктовку…": "Finishing dictation…",
        "Слушаю · ": "Listening · ",
        "Скрыть сообщение о диктовке": "Dismiss dictation notice",
        "Язык": "Language",
        "Микрофон в поле сообщения набирает текст. Отправляете его вы; API-ключ и лимиты ChatGPT для диктовки не нужны.": "The microphone in the message field types text. You send it yourself; dictation needs no API key or ChatGPT allowance.",
        "Распознавание выполняет Apple: на устройстве, если язык поддерживает этот режим, иначе — на серверах Apple. Аудиозапись в Proto-Mind не сохраняется.": "Apple performs recognition: on device when supported for the language, otherwise on Apple's servers. Proto-Mind does not save audio recordings.",
        "Закрыть историю": "Close history",
        "Название, текст или папка проекта": "Title, text or project folder",
        "Очистить поиск в истории": "Clear history search",
        "Показать": "Show",
        "Поиск в сохранённых диалогах…": "Searching saved conversations…",
        "Здесь появится ваша переписка": "Your conversations will appear here",
        "Совпадений нет": "No matches",
        "Можно искать слова из сообщений, название диалога или папку проекта.": "Search words from messages, conversation titles or project folders.",
        "Показать ещё": "Show more",
        "Поиск…": "Searching…",
        "Поиск на этом Mac · без запроса к модели": "Search on this Mac · no model call",
        "Черновик": "Draft",
        ", в архиве": ", archived",
        "Без папки проекта": "No project folder",
        "Предыдущее совпадение": "Previous match",
        "Следующее совпадение": "Next match",
        "Открыть это сообщение": "Open this message",
        "Последний запрос": "Latest request",
        "Последний ответ: ошибка": "Latest response: error",
        "Последний ответ": "Latest response",
        "Ответ на последний запрос не сохранён.": "No saved response to the latest request.",
        "Сообщений пока нет.": "No messages yet.",
        "Сохранённый черновик": "Saved draft",
        "Подготовить продолжение от ответа": "Prepare continuation from this response",
        "Откроется черновик с проверенным фрагментом прошлой работы. Следующую цель допишите перед отправкой; прежние вложения нужно выбрать заново.": "Opens a draft with a verified excerpt of earlier work. Add the next goal before sending; select previous attachments again if needed.",
        "Ваш черновик сохранится": "Your draft will be preserved",
        "Продолжить диалог": "Continue conversation",
        "К черновику": "Go to draft",
        "Ваше сообщение": "Your message",
        "Ошибка": "Error",
        "Ответ": "Response",
        "Фрагмент · полный текст в диалоге": "Excerpt · full text in conversation",
        "Сначала завершите голосовой разговор.": "End the voice conversation first.",
        "Разрешите облачную обработку в настройках и завершите восстановление данных.": "Allow cloud processing in Settings and finish data recovery.",
        "Разрешите микрофон для Proto-Mind в настройках конфиденциальности macOS.": "Allow Proto-Mind microphone access in macOS privacy settings.",
        "Поток микрофона остановился. Проверьте аудиоустройство и начните разговор снова.": "The microphone stream stopped. Check the audio device and start the conversation again.",
        "GPT Live не подтвердил подключение. Проверьте доступ API-ключа и баланс.": "GPT Live did not confirm the connection. Check the API key's access and balance.",
        "). Проверяй актуальное состояние через list_tasks.": "). Check the current state with list_tasks.",
        "Получен ответ по задаче": "A task response is ready",
        "Задача требует внимания": "A task needs attention",
        "Неверный звук в ответе GPT Live.": "Invalid audio in the GPT Live response.",
        "Вы": "You",
        "Слишком много одновременных голосовых команд.": "Too many simultaneous voice commands.",
        "Команда не завершилась. Можно уточнить её состояние голосом.": "The command did not finish. Ask for its status by voice.",
        "GPT Live сообщил об ошибке подключения.": "GPT Live reported a connection error.",
        "Выполняю команду…": "Running command…",
        "Команда принята": "Command accepted",
        "[ключ скрыт]": "[key hidden]",
        "Обновить файлы": "Refresh files",
        "Выбрать папку…": "Choose folder…",
        "Действия с файлами": "File actions",
        "Файлы рядом с разговором": "Files beside the conversation",
        "Выберите папку, чтобы читать документы и код.\nФайлы попадут в запрос только после прикрепления.": "Choose a folder to read documents and code.\nFiles enter a request only after you attach them.",
        "Открыть изображение или PDF…": "Open image or PDF…",
        "Родительская папка": "Parent folder",
        "Найти в этой папке": "Search this folder",
        "Очистить фильтр файлов": "Clear file filter",
        "В этой папке нет доступных файлов.": "No available files in this folder.",
        "Ничего не найдено.": "No matches.",
        "Показаны первые 400 файлов. Откройте вложенную папку, чтобы сузить список.": "Showing the first 400 files. Open a subfolder to narrow the list.",
        "Память": "Memory",
        "Цели": "Goals",
        "Долговременная и рабочая память. Поиск не изменяет записи.": "Long-term and working memory. Searching does not change records.",
        "Фокус и состояния целей. Никакого автоматического планирования.": "Goal focus and states. No automatic planning.",
        "Сохранённые описания и процедуры. Просмотр не запускает навык.": "Saved descriptions and procedures. Previewing does not run a skill.",
        "Текущие": "Current",
        "Все": "All",
        "Долговременная память": "Long-term memory",
        "Рабочая память": "Working memory",
        "Активно": "Active",
        "На паузе": "Paused",
        "Завершено": "Completed",
        "Отменено": "Cancelled",
        "Заменено": "Replaced",
        "Неактивно": "Inactive",
        "В архиве": "Archived",
        "Статус неизвестен": "Unknown status",
        "Высокий": "High",
        "Обычный": "Normal",
        "Низкий": "Low",
        "Неизвестно": "Unknown",
        "Неожиданный локальный capability-конверт. Данные не изменены.": "Unexpected local capability envelope. Data was not changed.",
        "Неожиданный контракт просмотра. Данные не изменены.": "Unexpected preview contract. Data was not changed.",
        "Содержание": "Content",
        "Описание": "Description",
        "Кратко": "Summary",
        "Текст навыка": "Skill text",
        "ID записи": "Record ID",
        "Источник": "Source",
        "Категория": "Category",
        "Важность": "Importance",
        "Сохранённая уверенность": "Saved confidence",
        "Вес": "Weight",
        "Дата записи": "Record date",
        "Создано": "Created",
        "Обновлено": "Updated",
        "Последнее использование": "Last used",
        "Счётчик использований": "Use count",
        "Заменено записью": "Replaced by record",
        "Дата замены": "Replacement date",
        "Причина замены": "Replacement reason",
        "Схема происхождения": "Provenance schema",
        "Схема жизненного цикла": "Lifecycle schema",
        "Неожиданный контракт карточки. Данные не изменены.": "Unexpected card contract. Data was not changed.",
        "Неожиданный контракт Memory Workshop. Ничего не выполнено.": "Unexpected Memory Workshop contract. Nothing was executed.",
        "Добавлено пользователем в память проекта.": "Added to project memory by the user.",
        "Заметка сохранена в памяти проекта.": "Note saved in project memory.",
        "Изменения сохранены. Прежняя версия осталась в истории.": "Changes saved. The previous version remains in history.",
        "Заметка проекта сохранена; модели не отправлялась": "Project note saved; not sent to a model",
        "Заметка убрана из памяти проекта. Вернуть её можно в истории.": "Note removed from project memory. Restore it from history if needed.",
        "Заметка снова доступна в памяти проекта.": "Note is available in project memory again.",
        "Можно выбрать не больше пяти заметок для одного сообщения.": "Select up to five notes for one message.",
        "Заметка выбрана только для следующего сообщения; отправьте его вручную": "Note selected for the next message only; send it manually",
        "Сначала выберите рабочую папку диалога.": "Choose a working folder for the conversation first.",
        "Язык системы": "System language",
        "Основной лимит": "Main allowance",
        "Дополнительный лимит": "Additional allowance",
    ]
}
