from __future__ import annotations


PILOT_COMMAND = "/warnings unknown"
DAILY_DOCTOR_COMMAND = "/daily doctor"
EXPORTS_DOCTOR_COMMAND = "/exports doctor"
CAPABILITIES_SAFETY_COMMAND = "/capabilities safety"
EVIDENCE_HISTORY_MAX_SIZE = 20
ACTIVE_READONLY_ALLOWLIST = (
    PILOT_COMMAND,
    DAILY_DOCTOR_COMMAND,
    EXPORTS_DOCTOR_COMMAND,
    CAPABILITIES_SAFETY_COMMAND,
)
EXACT_CONFIRMATION = f"CONFIRM RUN READONLY: {PILOT_COMMAND}"
DAILY_DOCTOR_CONFIRMATION = f"CONFIRM RUN READONLY: {DAILY_DOCTOR_COMMAND}"
EXPORTS_DOCTOR_CONFIRMATION = f"CONFIRM RUN READONLY: {EXPORTS_DOCTOR_COMMAND}"
CAPABILITIES_SAFETY_CONFIRMATION = f"CONFIRM RUN READONLY: {CAPABILITIES_SAFETY_COMMAND}"
EXACT_CONFIRMATIONS = {
    PILOT_COMMAND: EXACT_CONFIRMATION,
    DAILY_DOCTOR_COMMAND: DAILY_DOCTOR_CONFIRMATION,
    EXPORTS_DOCTOR_COMMAND: EXPORTS_DOCTOR_CONFIRMATION,
    CAPABILITIES_SAFETY_COMMAND: CAPABILITIES_SAFETY_CONFIRMATION,
}
RUN_USAGE = f"/runner-exec run {EXACT_CONFIRMATION}"
RUN_USAGES = tuple(f"/runner-exec run {EXACT_CONFIRMATIONS[command]}" for command in ACTIVE_READONLY_ALLOWLIST)
